  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements-ci.txt
  script:
    - python -m doctest -v fish_core/utils/common_utils.py
    - python -m doctest -v fish_core/simhash.py
    - python -m doctest -v fish_core/search_engine.py